LuxieApp/config/routes.rb
Rails.application.routes.draw do
	root 'luxies#index'
	
	get "/login" => "sessions#new", as: "login"
	delete "/logout" => "sessions#destroy", as: "logout"
	
	resources :sessions, only: [:new, :create, :destroy]
	
	resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
	
	resources :luxies do
		resources :service_categories, path: 'categories' do
			resources :services
		end
		
		resources :staff_members, path: 'staff'
		
		resource :store_info, path: 'info' do
			resource :address
			resources :hours_schedules, path: 'hours'
		end	
	end
			
	

end

LuxieApp/app/models/staff_member.rb
class StaffMember < ActiveRecord::Base
	belongs_to :luxie
end

LuxieApp/app/controllers/staff_members_controller.rb
class StaffMembersController < ApplicationController
  before_action :set_staff_member, only: [:show, :edit, :update, :destroy]

  # GET /staff_members
  # GET /staff_members.json
  def index
    @staff_members = StaffMember.all
  end

  # GET /staff_members/1
  # GET /staff_members/1.json
  def show
  end

  # GET /staff_members/new
  def new
    @staff_member = StaffMember.new
  end

  # GET /staff_members/1/edit
  def edit
  end

  # POST /staff_members
  # POST /staff_members.json
  def create
    @staff_member = StaffMember.new(staff_member_params)

    respond_to do |format|
      if @staff_member.save
        format.html { redirect_to @staff_member, notice: 'Staff member was successfully created.' }
        format.json { render :show, status: :created, location: @staff_member }
      else
        format.html { render :new }
        format.json { render json: @staff_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff_members/1
  # PATCH/PUT /staff_members/1.json
  def update
    respond_to do |format|
      if @staff_member.update(staff_member_params)
        format.html { redirect_to @staff_member, notice: 'Staff member was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff_member }
      else
        format.html { render :edit }
        format.json { render json: @staff_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staff_members/1
  # DELETE /staff_members/1.json
  def destroy
    @staff_member.destroy
    respond_to do |format|
      format.html { redirect_to staff_members_url, notice: 'Staff member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff_member
      @staff_member = StaffMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_member_params
      params.require(:staff_member).permit(:name, :title, :bio, :display_order)
    end
end

LuxieApp/app/helpers/staff_members_helper.rb
module StaffMembersHelper
end

LuxieApp/app/views/staff_members/_form.html.erb
<%= form_for(@staff_member) do |f| %>
  <% if @staff_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff_member.errors.count, "error") %> prohibited this staff_member from being saved:</h2>

      <ul>
      <% @staff_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :display_order %><br>
    <%= f.text_field :display_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

LuxieApp/app/views/staff_members/edit.html.erb
<h1>Editing Staff Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff_member %> |
<%= link_to 'Back', staff_members_path %>

LuxieApp/app/views/staff_members/index.html.erb
<h1>Listing Staff Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Bio</th>
      <th>Display order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staff_members.each do |staff_member| %>
      <tr>
        <td><%= staff_member.name %></td>
        <td><%= staff_member.title %></td>
        <td><%= staff_member.bio %></td>
        <td><%= staff_member.display_order %></td>
        <td><%= link_to 'Show', staff_member %></td>
        <td><%= link_to 'Edit', edit_staff_member_path(staff_member) %></td>
        <td><%= link_to 'Destroy', staff_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff member', new_staff_member_path %>

LuxieApp/app/views/staff_members/new.html.erb
<h1>New Staff Member</h1>

<%= render 'form' %>

<%= link_to 'Back', staff_members_path %>

LuxieApp/app/views/staff_members/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @staff_member.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @staff_member.title %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @staff_member.bio %>
</p>

<p>
  <strong>Display order:</strong>
  <%= @staff_member.display_order %>
</p>

<%= link_to 'Edit', edit_staff_member_path(@staff_member) %> |
<%= link_to 'Back', staff_members_path %>