LuxieApp/config/routes.rb
Rails.application.routes.draw do
	root 'luxies#index'
	
	get "/login" => "sessions#new", as: "login"
	delete "/logout" => "sessions#destroy", as: "logout"
	
	resources :sessions, only: [:new, :create, :destroy]
	
	resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
	
	resources :luxies do
		resources :service_categories, path: 'categories' do
			resources :services
		end
		
		resources :staff_members, path: 'staff'
		
		resource :store_info, path: 'info' do
			resource :address
			resources :hours_schedules, path: 'hours'
		end	
	end
			
	

end

LuxieApp/app/models/hours_schedule.rb
class HoursSchedule < ActiveRecord::Base
	belongs_to :store_info
	
	def formatted_hours
		if (self.open == "" || self.close == "") 
			return "CLOSED"
		elsif (self.open && self.close)
			return "#{self.open} - #{self.close}"	
		else
			return "CLOSED"
		end
	end
end

LuxieApp/app/controllers/hours_schedules_controller.rb
class HoursSchedulesController < ApplicationController
  before_action :set_luxie
	before_action :set_hours_schedule, only: [:show, :edit, :update, :destroy]

  # GET /hours_schedules
  # GET /hours_schedules.json
  def index
    @hours_schedules = @luxie.info.hours
  end

  # GET /hours_schedules/1
  # GET /hours_schedules/1.json
  def show
  end

  # GET /hours_schedules/new
  def new
    @hours_schedule = HoursSchedule.new
		@path = luxie_store_info_hours_schedules_path(@luxie)
  end

  # GET /hours_schedules/1/edit
  def edit
		@path = luxie_store_info_hours_schedule_path(@luxie, @hours_schedule)
  end

  # POST /hours_schedules
  # POST /hours_schedules.json
  def create
    @hours_schedule = @luxie.info.hours.new(hours_schedule_params)

    respond_to do |format|
      if @hours_schedule.save
        format.html { redirect_to luxie_store_info_hours_schedules_path(@luxie), notice: 'Hours schedule was successfully created.' }
        format.json { render :show, status: :created, location: @hours_schedule }
      else
        format.html { render :new }
        format.json { render json: @hours_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hours_schedules/1
  # PATCH/PUT /hours_schedules/1.json
  def update
    respond_to do |format|
      if @hours_schedule.update(hours_schedule_params)
        format.html { redirect_to luxie_store_info_hours_schedules_path(@luxie), notice: 'Hours schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @hours_schedule }
      else
        format.html { render :edit }
        format.json { render json: @hours_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours_schedules/1
  # DELETE /hours_schedules/1.json
  def destroy
    @hours_schedule.destroy
    respond_to do |format|
      format.html { redirect_to luxie_store_info_hours_schedules_url(@luxie), notice: 'Hours schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hours_schedule
      @hours_schedule = HoursSchedule.find(params[:id])
    end
	
		def set_luxie
			@luxie = Luxie.find(params[:luxie_id])
		end
	
    # Never trust parameters from the scary internet, only allow the white list through.
    def hours_schedule_params
      params.require(:hours_schedule).permit(:days, :open, :close, :store_info_id)
    end
end

LuxieApp/app/helpers/hours_schedules_helper.rb
module HoursSchedulesHelper
end

LuxieApp/app/views/hours_schedules/_form.html.erb
<!-- @path is defined in controller, based on whether it is a new action or an edit action -->
<%= form_for([@luxie, @hours_schedule], :url => @path) do |f| %>
  <% if @hours_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hours_schedule.errors.count, "error") %> prohibited this hours_schedule from being saved:</h2>

      <ul>
      <% @hours_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :days %><br>
    <%= f.text_field :days %>
  </div>
  <div class="field">
    <%= f.label :open %><br>
    <%= f.text_field :open %>
  </div>
  <div class="field">
    <%= f.label :close %><br>
    <%= f.text_field :close %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

LuxieApp/app/views/hours_schedules/edit.html.erb
<h1>Editing Hours Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back to Store Hours', luxie_store_info_hours_schedules_path(@luxie) %> |
<%= link_to 'Home', @luxie %>

LuxieApp/app/views/hours_schedules/index.html.erb
<h1><%= @luxie.info.name %>, Store Hours</h1>

<table style="border-spacing:10px;">
  <thead>
    <tr>
			<th>Days</th>
      <th>Hours</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @hours_schedules.each do |hours_schedule| %>
      <tr>
				<td style="text-align:right;"><strong><%= hours_schedule.days %></strong>:</td>
        <td><%= hours_schedule.formatted_hours %></td>
        <td><%= link_to 'Edit', edit_luxie_store_info_hours_schedule_path(@luxie, hours_schedule) %></td>
        <td><%= link_to 'Destroy', luxie_store_info_hours_schedule_path(@luxie, hours_schedule), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Home', @luxie %> | 
<%= link_to 'New Hours schedule', new_luxie_store_info_hours_schedule_path(@luxie) %>

LuxieApp/app/views/hours_schedules/new.html.erb
<h1>New Hours Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back to Store Hours', luxie_store_info_hours_schedules_path(@luxie) %> |
<%= link_to 'Home', @luxie %>

LuxieApp/app/views/hours_schedules/show.html.erb
<p>
  <strong>Days:</strong>
  <%= @hours_schedule.days %>
</p>

<p>
  <strong>Open:</strong>
  <%= @hours_schedule.open %>
</p>

<p>
  <strong>Close:</strong>
  <%= @hours_schedule.close %>
</p>

<%= link_to 'Edit', edit_hours_schedule_path(@hours_schedule) %> |
<%= link_to 'Back', hours_schedules_path %>